Export 2021/12/16
mozilla-l10n/firefoxios-l10n pull request #124
Opened 2021-12-16 21:20 UTC by nishant2718

This export is to correct the issue with deleted locales - those strings should be part of this and available for translations now.

2021-12-21 06:32 UTC, flodolo requested changes
This is not OK.

You based your PR on an obsolete version, so you're removing or reverting a ton of translations.

On top of that, you're once again removing **all** translations for some locales, which I had to manually fix last time.
https://github.com/mozilla-l10n/firefoxios-l10n/pull/123

2021-12-21 06:32 UTC, flodolo commented on cs/firefox-ios.xliff
> -        <target>Pro ukládání a automatické vyplňování přihlašovacích údajů si na svém zařízení nastavte Face ID, Touch ID nebo kód zámku.</target>
These translations should not be removed. My guess is that you did your export on an obsolete version of the repository (these strings were approved almost 2 weeks ago, Dec 8).

Please update the repository and redo the export

2021-12-21 06:32 UTC, flodolo commented on co/firefox-ios.xliff
> +        <target>Scrivite u codice d’accessu</target>
Same here, you're reverting translations that were changed recently.

2021-12-21 06:32 UTC, flodolo commented on bn/firefox-ios.xliff
> -        <target>যোগ করুন</target>
This is removing once again all the translations.

2021-12-21 08:20 UTC, flodolo commented
> On top of that, you're once again removing **all** translations for some locales, which I had to manually fix last time.
> #123

Correction: this is not true, I was fooled by changes in `bn`, but for these locales the PR is also changing the order of attributes.

So, exporting on top of the latest version of the l10n repo should work.

2021-12-21 22:15 UTC, nishant2718 commented
Sorry for the delayed reply! I made sure to rebase and pull the latest changes at that time (Dec 16) when I made the PR. I can definitely do a new export and pull the latest changes (of whenever that export date is) as well, if it's needed.

2021-12-22 06:32 UTC, flodolo commented
> Sorry for the delayed reply! I made sure to rebase and pull the latest changes at that time (Dec 16) when I made the PR.

This is not possible. Check the blame for the Czech string I pointed out, it was committed on Dec 8
https://github.com/mozilla-l10n/firefoxios-l10n/commit/f82ed86d24152fc024b7bee8af008c9263ff5ed3

> I can definitely do a new export and pull the latest changes (of whenever that export date is) as well, if it's needed.

I don't know enough about iOS, but I assume you need to import the latest strings first, then export.

With that said, is this really urgent? There is only 1 new string ("Older"), and the repository is [actively worked on](https://github.com/mozilla-l10n/firefoxios-l10n/commits/master), which makes merging really complicated (pull requests will get merge conflicts, and the only people who can help are either on PTO or based in EU).

2022-01-04 18:18 UTC, Delphine commented
Thanks for jumping in with this flod.
@nishant2718 : I think we should just close this and make the new string here as part of a new export, the next time we do one for a new release.
It seems the issue may have been that you need to import latest localizations from our repo, before you make an export from your side.
FWIW I believe there used to be docs for l10n and iOS... but not sure how updated they are. Would be good to see if they need to be udpated.
thanks!

2022-01-04 18:18 UTC, closed without merging