Extract new strings (2023-04-18)
mozilla-l10n/firefoxios-l10n pull request #189
Opened 2023-04-18 15:06 UTC by mozilla-pontoon

Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

2023-04-18 18:22 UTC, Delphine requested changes
@adudenamedruby @thatswinnie Not sure who landed the strings, but there is one needing a quick fix: just needs a bit more clarification about what "Tip" is in the localization comment. Thank you!

2023-04-19 19:54 UTC, thatswinnie commented on en-US/firefox-ios.xliff
> +        <note>Fallback Title of notification if no notification title was configured. The argument is the app name.</note>
@Delphine I added more context. The PR for that is merged on main and the backport to the release branch is merged as well.

2023-04-19 20:24 UTC, Delphine commented on en-US/firefox-ios.xliff
> +        <note>Fallback Title of notification if no notification title was configured. The argument is the app name.</note>
Thank you! I'll trigger a string import again now.

2023-04-19 20:41 UTC, Delphine approved these changes

2023-04-19 20:41 UTC, merged